context:
  colors:
    Primary:
      Primary Black:
        var: "$primary-black"
        hex: "#1a1919"
        rgb: "26,25,25"
      Primary Orange:
        var: "$orange"
        hex: "#ff5f14"
        rgb: "255,103,32"
      Primary Cream:
        var: "$cream"
        hex: "#f3f0eb"
        rgb: "243,240,235"
    Warm Neutrals:
      Neutral 1:
        var: "$neutral-1"
        hex: "#382e2c"
        rgb: "56,46,44"
      Neutral 2:
        var: "$neutral-2"
        hex: "#5e514d"
        rgb: "94,81,77"
      Neutral 3:
        var: "$neutral-3"
        hex: "#6e6259"
        rgb: "110,98,89"
      Neutral 4:
        var: "$neutral-4"
        hex: "#83786f"
        rgb: "131,120,111"
      Neutral 5:
        var: "$neutral-5"
        hex: "#968c83"
        rgb: "150,140,131"
      Neutral 6:
        var: "$neutral-6"
        hex: "#aca39a"
        rgb: "172,163,154"
      Neutral 7:
        var: "$neutral-7"
        hex: "#bfb8af"
        rgb: "191,184,175"
      Neutral 8:
        var: "$neutral-8"
        hex: "#d7d2cb"
        rgb: "215,210,203"
    Extended Palette:
      Black:
        var: "$black"
        hex: "#000"
        rgb: "0,0,0"
      Neutral Black:
        var: "$neutral-black"
        hex: "#222"
        rgb: "34,34,34"
      White:
        var: "$white"
        hex: "#fff"
        rgb: "255,255,255"
      Blue:
        var: "$blue"
        hex: "#009cde"
        rgb: "0,156,222"
      Dark Orange:
        var: "$dark-orange"
        hex: "#fe5000"
        rgb: "254,80,0"
      Light Orange:
        var: "$light-orange"
        hex: "#ff8f1c"
        rgb: "255,143,28"
