title: Heads Up Card
context:
  name: Jane Smith
  type: Vice President
  phone: (555) 555-5555
  avatar: https://aquent.com/contentAsset/image/f3cbfdf1-5ce3-4edb-9895-08651f3871a8/picture/byInode/1/filter/Resize,Jpeg/resize_w/413/resize_h/315/jpeg_q/75/v/pic.jpg
