title: Side-by-Side Content Panels
context:
  panelLeft: https://stag.aquent.fr/dA/9292dd295a/talent-career.jpg
  panelRight: <div class="text-center"><h2 class="fixed-size-x-large font-wide">CARRIÈRE</h2><p>Nous offrons à nos talents la possibilité de travailler pour les plus grands noms, autour du globe. Nous leur offrons régulièrement des opportunités les incitant à se challenger eux-mêmes, mais toujours avec le soutien nécessaire, afin de répondre aux besoins de nos clients jour après jour.</p></div>
  panelLeftType: image
  panelRightType: copy
